from flask import Flask, jsonify
import os

app = Flask(__name__)

@app.route('/vin', methods=['GET'])
def get_vin_data():
    response_data = {
        "Count": 1,
        "Message": "Results returned successfully. NOTE: Any missing decoded values should be interpreted as NHTSA does not have data on the specific variable. Missing value should NOT be interpreted as an indication that a feature or technology is unavailable for a vehicle.",
        "SearchCriteria": "VIN(s): 4V4NC9JH21N322086",
        "Results": [
            {
                "ABS": "",
                "ActiveSafetySysNote": "",
                "AdaptiveCruiseControl": "",
                "AdaptiveDrivingBeam": "",
                "AdaptiveHeadlights": "",
                "AdditionalErrorText": "",
                "AirBagLocCurtain": "",
                "AirBagLocFront": "",
                "AirBagLocKnee": "",
                "AirBagLocSeatCushion": "",
                "AirBagLocSide": "",
                "AutoReverseSystem": "",
                "AutomaticPedestrianAlertingSound": "",
                "AxleConfiguration": "",
                "Axles": "",
                "BasePrice": "",
                "BatteryA": "",
                "BatteryA_to": "",
                "BatteryCells": "",
                "BatteryInfo": "",
                "BatteryKWh": "",
                "BatteryKWh_to": "",
                "BatteryModules": "",
                "BatteryPacks": "",
                "BatteryType": "",
                "BatteryV": "",
                "BatteryV_to": "",
                "BedLengthIN": "",
                "BedType": "",
                "BlindSpotIntervention": "",
                "BlindSpotMon": "",
                "BodyCabType": "MDHD: Conventional",
                "BodyClass": "Truck-Tractor",
                "BrakeSystemDesc": "",
                "BrakeSystemType": "Air",
                "BusFloorConfigType": "Not Applicable",
                "BusLength": "",
                "BusType": "Not Applicable",
                "CAN_AACN": "",
                "CIB": "",
                "CashForClunkers": "",
                "ChargerLevel": "",
                "ChargerPowerKW": "",
                "CombinedBrakingSystem": "",
                "CoolingType": "",
                "CurbWeightLB": "",
                "CustomMotorcycleType": "Not Applicable",
                "DaytimeRunningLight": "",
                "DestinationMarket": "",
                "DisplacementCC": "14000",
                "DisplacementCI": "854.3324173262",
                "DisplacementL": "14",
                "Doors": "",
                "DriveType": "6x4",
                "DriverAssist": "",
                "DynamicBrakeSupport": "",
                "EDR": "",
                "ESC": "",
                "EVDriveUnit": "",
                "ElectrificationLevel": "",
                "EngineConfiguration": "In-Line",
                "EngineCycles": "4",
                "EngineCylinders": "6",
                "EngineHP": "425",
                "EngineHP_to": "474",
                "EngineKW": "",
                "EngineManufacturer": "Cummins",
                "EngineModel": "N14",
                "EntertainmentSystem": "",
                "ErrorCode": "0",
                "ErrorText": "0 - VIN decoded clean. Check Digit (9th position) is correct",
                "ForwardCollisionWarning": "",
                "FuelInjectionType": "",
                "FuelTankMaterial": "",
                "FuelTankType": "",
                "FuelTypePrimary": "Diesel",
                "FuelTypeSecondary": "",
                "GCWR": "",
                "GCWR_to": "",
                "GVWR": "Class 8: 33,001 lb and above (14,969 kg and above)",
                "GVWR_to": "",
                "KeylessIgnition": "",
                "LaneCenteringAssistance": "",
                "LaneDepartureWarning": "",
                "LaneKeepSystem": "",
                "LowerBeamHeadlampLightSource": "",
                "Make": "VOLVO TRUCK",
                "MakeID": "487",
                "Manufacturer": "VOLVO GROUP NORTH AMERICA, LLC",
                "ManufacturerId": "1015",
                "Model": "VNL",
                "ModelID": "1967",
                "ModelYear": "2001",
                "MotorcycleChassisType": "Not Applicable",
                "MotorcycleSuspensionType": "Not Applicable",
                "NCSABodyType": "",
                "NCSAMake": "",
                "NCSAMapExcApprovedBy": "",
                "NCSAMapExcApprovedOn": "",
                "NCSAMappingException": "",
                "NCSAModel": "",
                "NCSANote": "",
                "NonLandUse": "",
                "Note": "Cab Type: Conventional - New Generation",
                "OtherBusInfo": "",
                "OtherEngineInfo": "",
                "OtherMotorcycleInfo": "",
                "OtherRestraintSystemInfo": "",
                "OtherTrailerInfo": "",
                "ParkAssist": "",
                "PedestrianAutomaticEmergencyBraking": "",
                "PlantCity": "NEW RIVER VALLEY DUBLIN",
                "PlantCompanyName": "",
                "PlantCountry": "UNITED STATES (USA)",
                "PlantState": "VIRGINIA",
                "PossibleValues": "",
                "Pretensioner": "",
                "RearAutomaticEmergencyBraking": "",
                "RearCrossTrafficAlert": "",
                "RearVisibilitySystem": "",
                "SAEAutomationLevel": "",
                "SAEAutomationLevel_to": "",
                "SeatBeltsAll": "",
                "SeatRows": "",
                "Seats": "",
                "SemiautomaticHeadlampBeamSwitching": "",
                "Series": "",
                "Series2": "",
                "SteeringLocation": "",
                "SuggestedVIN": "",
                "TPMS": "",
                "TopSpeedMPH": "",
                "TrackWidth": "",
                "TractionControl": "",
                "TrailerBodyType": "Not Applicable",
                "TrailerLength": "",
                "TrailerType": "Not Applicable",
                "TransmissionSpeeds": "",
                "TransmissionStyle": "",
                "Trim": "",
                "Trim2": "",
                "Turbo": "",
                "VIN": "4V4NC9JH21N322086",
                "ValveTrainDesign": "",
                "VehicleDescriptor": "4V4NC9JH*1N",
                "VehicleType": "TRUCK",
                "WheelBaseLong": "",
                "WheelBaseShort": "",
                "WheelBaseType": "",
                "WheelSizeFront": "",
                "WheelSizeRear": "",
                "WheelieMitigation": "",
                "Wheels": "",
                "Windows": ""
            }
        ]
    }
    return jsonify(response_data)

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port)
